"""add_annotation_type_column

Revision ID: 83f934edc6b6
Revises: a1b2c3d4e5f6
Create Date: 2026-06-10 21:40:01.155478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '83f934edc6b6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('annotation_type', sa.Text(), server_default='extraction', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'annotation_type')
    # ### end Alembic commands ###
